name: État et révolution numérique
markdown: redcarpet
pygments: true
permalink: /blog/:categories/:year/:month/:day/:title.html
url: http://www.numascpo.net
base_url: /

title: "État et révolution numérique"
description: "Site de la conférence de méthode du Master d'affaires publiques de SciencesPo Paris"

toplinks: ['blog', 'pays', 'calendrier', 'licence']

licences:
    - langue: français
      pdf: Licence-Ouverte-Open-Licence.pdf
      rtf: Licence-Ouverte-Open-Licence.rtf
      
    - langue: anglais
      pdf: Licence-Ouverte-Open-Licence-ENG.pdf
      rtf: Licence-Ouverte-Open-Licence-ENG.rtf

seances:
    - seance: 1
      date: 21 janvier
      titre: Introduction

    - seance: 2
      date: 28 janvier
      titre: Transformation numérique des organisations

    - seance: 3
      date: 4 février
      titre: Liberté, justice, sécurité et défense

    - seance: 4
      date: 11 février
      titre: Numérique et questions internationales

    - seance: 5
      date: 18 février
      titre: Citoyenneté, gouvernance publique et démocratie

    - seance: 6
      date: 4 mars
      titre: La politique culturelle 2.0

    - seance: 7
      date: 11 mars
      titre: Apprendre, enseigner et partager au XXIe siècle

    - seance: 8
      date: 18 mars
      titre: Les enjeux sanitaires et sociaux

    - seance: 9
      date: 25 mars
      titre: Un levier de croissance économique

    - seance: 10
      date: 1 avril
      titre: Territoires numériques

    - seance: 11
      date: 8 avril
      titre: Présentation des mémoires collectifs

    - seance: 12
      date: 15 avril
      titre: Stratégie numérique de l’État

